# .github/workflows/build-ics.yml
name: Build ICS
on:
  schedule: [{ cron: "0 6 * * *" }]  # 06:00 UTC daily
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: python scripts/build_ics.py  # generates shropshire_events_JonnyUtah100pc.ics with STABLE UIDs
      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add shropshire_events_JonnyUtah100pc.ics
          git commit -m "auto: refresh ICS" || echo "No changes"
          git push
